---
title: "COVID Plot"
author: "Aidan Boland"
date: "10/5/2020"
output: html_document
---

```{r setup, include=TRUE, warning = F}
library(dplyr)
library(ggplot2)
library(sf)
```

```{r get spatial data}
# The data must be downloaded and unzipped, there are multiple files in the zip which are needed
directory_to_use <- "data"
download.file("https://opendata.arcgis.com/datasets/27d401c9ae084097bb1f3a69b69462a1_0.zip?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D", 
              file.path(directory_to_use, paste0("Covid19_LEACases_Mapped_", Sys.Date() ,".zip")))
utils::unzip(file.path(directory_to_use, paste0("Covid19_LEACases_Mapped_", Sys.Date() ,".zip")), exdir = directory_to_use)

electoral_data <- 
  st_read(file.path(directory_to_use, "Covid19_LEACases_Mapped.shp"), stringsAsFactors = F) %>%
  mutate(EventDate = as.Date(EventDate))

# electoral_data_csv <- readr::read_csv("https://opendata.arcgis.com/datasets/27d401c9ae084097bb1f3a69b69462a1_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D")
# write.csv(electoral_data_csv, file = paste0("data/electoral_data_", max(electoral_data$EventDate), ".csv"))

date_to_use <- max(electoral_data$EventDate)

electoral14_plot <- 
  electoral_data %>%
  filter(EventDate == max(EventDate)) %>%
  ggplot() + 
  geom_sf(aes(fill = P14_100k), colour = NA) + 
  theme_void() +
  scale_fill_distiller(palette = "RdYlGn",
                       limits = c(0, NA)) +
  coord_sf(ndiscr = F) +
  labs(title = paste0("Republic of Ireland  ", format(date_to_use - 14, "%d/%m"), " - ", format(date_to_use, "%d/%m")),
       subtitle = 'COVID Cases Per 100,000 (14 Day Incidence)', 
       fill = "")

ggsave(filename = file.path(directory_to_use, paste0("electoral_data_",Sys.Date(),".png")), 
       plot = electoral14_plot, dpi = 1200)

```



```{r}

max_val <- max(electoral_data$P14_100k)
max_val <- 2000


utils::unzip(file.path(directory_to_use, paste0("Covid19_LEACases_Mapped_2020-10-22.zip")), exdir = directory_to_use)

electoral_data <- 
  st_read(file.path(directory_to_use, "Covid19_LEACases_Mapped.shp"), stringsAsFactors = F) %>%
  mutate(EventDate = as.Date(EventDate))

date_to_use <- max(electoral_data$EventDate)

electoral14_plot_1005 <- 
  electoral_data %>%
  filter(EventDate == max(EventDate)) %>%
  ggplot() + 
  geom_sf(aes(fill = P14_100k), colour = NA) + 
  theme_void() +
  scale_fill_distiller(palette = "RdYlGn",
                       limits = c(-3, max_val)) +
  coord_sf(ndiscr = F) +
  labs(title = paste0("Republic of Ireland  ", format(date_to_use - 14, "%d/%m"), " - ", format(date_to_use, "%d/%m")),
       subtitle = 'COVID Cases Per 100,000 (14 Day Incidence)', 
       fill = "")

ggsave(filename = paste0("data/2electoral_10-12_",Sys.Date(),".png"), 
       plot = electoral14_plot_1005, dpi = 1200)



utils::unzip(file.path(directory_to_use, paste0("Covid19_LEACases_Mapped_2020-10-09.zip")), exdir = directory_to_use)

electoral_data <- 
  st_read(file.path(directory_to_use, "Covid19_LEACases_Mapped.shp"), stringsAsFactors = F) %>%
  mutate(EventDate = as.Date(EventDate))

date_to_use <- max(electoral_data$EventDate)

electoral14_plot_1005 <- 
  electoral_data %>%
  filter(EventDate == max(EventDate)) %>%
  ggplot() + 
  geom_sf(aes(fill = P14_100k), colour = NA) + 
  theme_void() +
  scale_fill_distiller(palette = "RdYlGn",
                       limits = c(-3, max_val)) +
  coord_sf(ndiscr = F) +
  labs(title = paste0("Republic of Ireland  ", format(date_to_use - 14, "%d/%m"), " - ", format(date_to_use, "%d/%m")),
       subtitle = 'COVID Cases Per 100,000 (14 Day Incidence)', 
       fill = "")

ggsave(filename = paste0("data/2electoral_10-05_",Sys.Date(),".png"), 
       plot = electoral14_plot_1005, dpi = 1200)
```

