---
title: "COVID in Ireland"
author: "Aidan Boland"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# data tidy
library(dplyr)

# rolling sums
library(zoo)

# animation
library(ggplot2)
library(gganimate)
library(transformr)

# Needed but not loaded
require(rgdal)
require(broom)
require(readr)
require(tidyr)
```

Information on the data can be found at [this link](https://data.gov.ie/dataset/covid19countystatisticshpscireland).

```{r get spatial data}
# The data must be downloaded and unzipped, there are multiple files in the zip which are needed
directory_to_use <- "data/"
# download.file("https://opendata.arcgis.com/datasets/d9be85b30d7748b5b7c09450b8aede63_0.zip?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D",
#               file.path(directory_to_use, "Covid19CountyStatisticsHPSCIreland.zip"))
# utils::unzip(file.path(directory_to_use, "Covid19CountyStatisticsHPSCIreland.zip"), 
#              exdir = directory_to_use)
# covid_openddata_shpdata <-  rgdal::readOGR(dsn = file.path(directory_to_use, "Covid19CountyStatisticsHPSCIreland.shp"), stringsAsFactors = F)

# Create data frame containing the polygon coordinates
# county_polygon_data <- broom::tidy(covid_openddata_shpdata, region = "CountyName")
# write.csv(county_polygon_data, file = file.path(directory_to_use, "county_polygon.csv"), row.names = F) # Optional save county polygon data
county_polygon_data <- readr::read_csv("data/county_polygon.csv")
```


```{r covid numbers}
# # Create data frame of the covid stats only, no spatial data
# county_csv <- 
#   covid_openddata_shpdata@data  %>%
#   rename(PopulationCensus16 = Population, ConfirmedCovidCases = ConfirmedC)

# A more up to date dataset (without spatial data)
county_csv <- 
  readr::read_csv("http://opendata-geohive.hub.arcgis.com/datasets/d9be85b30d7748b5b7c09450b8aede63_0.csv?outSR={%22latestWkid%22:3857,%22wkid%22:102100}") %>%
  mutate(TimeStamp = as.Date(TimeStamp))

testing_csv <- 
  readr::read_csv("http://opendata-geohive.hub.arcgis.com/datasets/f6d6332820ca466999dbd852f6ad4d5a_0.csv?outSR={%22latestWkid%22:3857,%22wkid%22:102100}") %>%
  mutate(Date_HPSC = as.Date(Date_HPSC))

hospital_csv <- 
  readr::read_csv("http://opendata-geohive.hub.arcgis.com/datasets/fe9bb23592ec4142a4f4c2c9bd32f749_0.csv?outSR={%22latestWkid%22:4326,%22wkid%22:4326}") %>%
  mutate(Date = as.Date(Date))

icu_csv <- 
  readr::read_csv("https://opendata.arcgis.com/datasets/c8208a0a8ff04a45b2922ae69e9b2206_0.csv")

```


```{r tidy and wrangle}
covid_rolling14 <- 
  county_csv %>%
  # Remove unneeded columns and parse date
  select(CountyName, TimeStamp, PopulationCensus16, ConfirmedCovidCases) %>%
  
  # Add any missing dates and fill the data for missing dates
  group_by(CountyName) %>%
  tidyr::complete(TimeStamp = seq(min(as.Date(.$TimeStamp)), # use .$TimeStamp to get global data min 
                                  max(as.Date(.$TimeStamp)), # not just the min for the group_by var
                                  by = "day")) %>%
  # Ensure the data is arranged by date
  arrange(TimeStamp) %>%
  tidyr::fill(PopulationCensus16, ConfirmedCovidCases, .direction = "down") %>%
  
  # Calculate the lag and then the cases per day
  mutate(lag_cases = lag(ConfirmedCovidCases, 1, default = 0),
         new_cases = ConfirmedCovidCases - lag_cases,
         new_cases_per100 = 100000 * (new_cases/PopulationCensus16),
         
         # Rolling 14 Day Total
         rolling14 = rollsum(new_cases, 14, align = "right", fill = 0),
         rolling14_per100 = rollsum(new_cases_per100, 14, align = "right", fill = 0),
         mean_rolling14_per100 = rollsum(new_cases_per100, 14, align = "right", fill = 0)/14) %>%
  ungroup()
```



## Animation

```{r map animation}
# Animation
rolling14_anim <- 
  covid_rolling14 %>%
  # Filter the data by date
  filter(TimeStamp >= "2020-08-01") %>% # Sys.Date() - 50
  # Join data to county map data
  full_join(county_polygon_data, by = c("CountyName" = "id")) %>%
  ggplot() + geom_polygon(aes(x = long, y = lat, group = group, fill = mean_rolling14_per100), colour = "black") + 
  theme_void() +
  theme(text = element_text(size = 14)) +
  scale_fill_distiller(palette = "RdYlGn",
                       limits = c(0, max(covid_rolling14$mean_rolling14_per100)),
                      ) +
  coord_quickmap() +
  # -Animation-
  # Plot elements for animation
  transition_time(TimeStamp) +
  labs(title = "Republic of Ireland - {format(frame_time, '%B %d')}",
       subtitle = 'COVID Cases Per 100,000 (14 Day Average)', 
       fill = "")

# # Create the animation, nframes and fps will set the speed of the animation
# # This can be slow depending on choices
# map_anim <- 
#   animate(rolling14_anim, 
#           nframes = 120, fps = 10,
#           start_pause = 5, end_pause = 20)
# 
# anim_save(filename = paste0(directory_to_use, "rolling_14day_", Sys.Date(),".gif"),
#           animation = map_anim)
# 
# map_anim
```



# Testing Data

```{r}



# stats_to_include <- c("hospital_cases", "rolling14_positive",  "rolling14_labs", "roling14_percentage")
stats_key <- 
  c("hospital_cases" = "Cases in Hospitals",
    #"rolling14_labs" = "Tests (14 Day Average)", 
    "rolling14_positive" = "Positive Tests (14 Day Average)",
    "roling14_percentage" = "% Positive Tests (14 Day Average)")


testing_tidy <- 
  testing_csv %>%
  arrange(Date_HPSC) %>%
  mutate(daily_labs = TotalLabs - lag(TotalLabs),
         daily_positive = Positive - lag(Positive),
         rolling14_labs = rollsum(daily_labs, 14, align = "right", fill = 0)/14,
         rolling14_positive = rollsum(daily_positive, 14, align = "right", fill = 0)/14,
         roling14_percentage = 100*(rolling14_positive/rolling14_labs)) %>%
  left_join(hospital_csv %>%
              select(Date, 
                     hospital_cases = SUM_number_of_confirmed_covid_1,
                     hospital_new = SUM_no_new_admissions_covid19_p),
            by = c("Date_HPSC" = "Date")) %>%
  tidyr::pivot_longer(cols = names(stats_key), 
                      names_to = "stat", values_to = "rolling14") %>%
  mutate(stat = recode_factor(stat, !!!stats_key, .ordered = TRUE))


testing_14_anim <- 
  testing_tidy %>%  
  filter(Date_HPSC >= "2020-08-01") %>% #, Date_HPSC <= max(covid_rolling14$TimeStamp)
  ggplot(aes(x = Date_HPSC, y = rolling14), colour = "black") +
  geom_line() +
  geom_point(colour = "darkgreen") +
  scale_y_continuous(position = c("right"), limits = c(0, NA)) +
  facet_wrap(~stat, ncol = 1, scales = "free") +
  labs(x = "", y = "", title = "Stats") +
  theme_light() +
  theme(text = element_text(size = 14),
        strip.text.x = element_text(size = 16)) +
  transition_reveal(Date_HPSC) + 
  labs(title = "National Statistics",
       subtitle = 'Data: https://opendata-geohive.hub.arcgis.com/',
       x = "", y = "")


# test_anim <- 
#   animate(testing_14_anim,
#         nframes = 120, fps = 10,
#           start_pause = 5, end_pause = 20)
# 
# anim_save(filename = paste0(directory_to_use, "rolling_14day_tests_", Sys.Date(),".gif"),
#           animation = map_anim)
# 
# test_anim
```




```{r combined gif, eval = F}
library(magick)

gif_length_sec = 10
gif_fps = 10
start_pause_sec <- 1
end_pause_sec <-  5
gif_frames = gif_length_sec * gif_fps

map_ndates <- covid_rolling14 %>% filter(TimeStamp >= "2020-08-01") %>% select(TimeStamp) %>% distinct() %>% nrow()
stat_ndates <- testing_tidy %>% filter(Date_HPSC >= "2020-08-01") %>% select(Date_HPSC) %>% distinct() %>% nrow()

if(stat_ndates > map_ndates){
  map_pause = ceiling((gif_fps * end_pause_sec) * (1+(stat_ndates - map_ndates)/map_ndates))
  stat_pause =  gif_fps * end_pause_sec
}


map_anim2 <- 
  animate(rolling14_anim, 
          nframes = gif_frames, 
          fps = gif_fps,
          start_pause = start_pause_sec * gif_fps, 
          end_pause = map_pause,
          renderer = magick_renderer())

test_anim2 <- 
  animate(testing_14_anim,
          nframes = gif_frames, 
          fps = gif_fps,
          start_pause = start_pause_sec * gif_fps, 
          end_pause = stat_pause, 
        renderer = magick_renderer())

new_gif <- image_append(c(map_anim2[1], test_anim2[1]))
for(i in 2:gif_frames){
  combined <- image_append(c(map_anim2[i], test_anim2[i]))
  new_gif <- c(new_gif, combined)
}

magick::image_write_gif(new_gif, 
                        path = paste0(directory_to_use, "rolling_14day_combined_", Sys.Date(),".gif"),
                        delay = 1/10)

new_gif
```
