---
title: "Food Consumption"
author: "Aidan Boland"
date: "10/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(knitr)
library(dplyr)
library(ggplot2)
```

## Data

A pre-cleaned version of the data can be loaded using the following command.

```{r load data}
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
```



```{r}
head(food_consumption)
```


```{r}
food_consumption %>%
  ggplot(aes(x = consumption, y = co2_emmission, colour = food_category)) + 
  geom_point()
```



```{r}
library(scales)

food_consumption %>%
  ggplot(aes(x = consumption, y = food_category, colour = food_category)) + 
  geom_point() +
  theme(legend.position = "none") +
  labs(x = "Consumption (kg/person/year)", y = "Food Type") +
  scale_x_continuous(label = number_format(suffix = " kg"))
```

```{r}
food_consumption %>%
  ggplot(aes(x = co2_emmission, y = food_category, colour = food_category)) + 
  geom_point() +
  theme(legend.position = "none") +
  labs(x = "Emmission (CO2 kg/person/year)", y = "Food Type") +
  scale_x_continuous(label = comma_format(suffix = " kg"))
```



### Summary Statistics


```{r}
food_summary <- 
  food_consumption %>%
  group_by(country) %>%
  summarise(average_emmission = mean(co2_emmission), 
            total_emmissions = sum(co2_emmission)) 


food_summary %>%
  arrange(desc(average_emmission)) %>%
  head(10)

food_summary %>%
  arrange(desc(total_emmissions)) %>%
  head(10)

food_summary %>%
  arrange(desc(total_emmissions)) %>%
  tail(10)

food_summary %>%
  arrange(total_emmissions) %>%
  head(10)
```





```{r}
food_consumption %>%
  group_by(food_category) %>%
  summarise(average_consumption = mean(consumption)) %>%
  arrange(desc(average_consumption)) %>%
  rename(`Food Type` = food_category, `Mean Consumption` = average_consumption) %>%
  kable()
```


## Maps


```{r}
library(maps)

world_map <- map_data("world")

ggplot() + 
  geom_polygon(data = world_map, 
               aes(x = long, y = lat, group = group), fill = NA, color = "black") 


food_consumption_summary <- 
  food_consumption %>%
  group_by(country) %>%
  summarise(average_emmission = mean(co2_emmission), 
            total_emmissions = sum(co2_emmission)) 

food_consumption_map <- food_consumption_summary %>%
  inner_join(world_map, by = c("country" = "region"))
  

ggplot() + 
  geom_polygon(data = food_consumption_map, 
               aes(x = long, y = lat, group = group, fill = total_emmissions)) +
  scale_fill_distiller(palette = "Spectral", label = comma_format(suffix = " kg/per/persion")) +
  coord_fixed(1.3) +
  theme_void() +
  labs(fill = "Total Emmisions (CO2 kg/per)")
```




```{r}
food_consumption %>%
  filter(food_category == "Beef") %>%
  inner_join(world_map, by = c("country" = "region")) %>%
  ggplot(aes(x = long, y = lat, group = group, fill = co2_emmission)) + 
  geom_polygon() +
  scale_fill_distiller(palette = "Spectral", label = comma_format(suffix = " kg/per/persion")) +
  coord_fixed(1.3) +
  theme_void() +
  labs(fill = "Beef Emmission")
```



