---
title: "Covid Ireland"
author: "Aidan Boland"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(knitr)
```

```{r}
# http://opendata-geohive.hub.arcgis.com/datasets/4779c505c43c40da9101ce53f34bb923_0.csv?outSR={%22latestWkid%22:3857,%22wkid%22:102100}
covid_raw <- readr::read_csv("http://opendata-geohive.hub.arcgis.com/datasets/4779c505c43c40da9101ce53f34bb923_0.csv?outSR={%22latestWkid%22:3857,%22wkid%22:102100}")

head(covid_raw) %>%
  select(TimeStampDate, CountyName, PopulationCensus16, Lat, Long, ConfirmedCovidCases, PopulationProportionCovidCases) %>%
  kable()
```


```{r}
#covid_raw$TimeStampDate

library(lubridate)

#mode(covid_raw$TimeStampDate[1:5])
#as_date(ymd_hms(covid_raw$TimeStampDate[1:5]))

covid_tidy <-
  covid_raw %>%
  mutate(date = as_date(ymd_hms(TimeStampDate)))
head(covid_tidy) %>%
  select(date, CountyName, PopulationCensus16, Lat, Long, ConfirmedCovidCases, PopulationProportionCovidCases) %>%
  kable()
```

# Map per County

```{r}
library(maps)

ireland <- map_data("world") %>%
  filter(region == "Ireland")

covid_latest <-
  covid_tidy %>%
  filter(date == max(date))

ireland %>%
ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group), fill = NA, colour = "black") +
  coord_fixed(1.3) +
  geom_point(data = covid_latest, aes(y = Lat, x = Long, size = PopulationProportionCovidCases), colour = "cornflowerblue") +
  labs(title = paste("Population Proportion of Covid by County for", 
                     format(unique(covid_latest$date), "%b %d")), 
       size = "Pop Proportion (per 100,000)") +
  theme_void()
```


```{r}
covid_tidy %>%
  filter(ConfirmedCovidCases > 0) %>%
  ggplot(aes(x = date, y = PopulationProportionCovidCases, colour = CountyName)) +
  geom_point()
```


```{r}

covid_total <- 
  covid_tidy %>%
  filter(ConfirmedCovidCases > 0) %>%
  group_by(date) %>%
  summarise(total_confirmed = sum(ConfirmedCovidCases))


covid_total %>%
  ggplot(aes(x = date, y = total_confirmed)) +
  geom_point() +
  labs(y = 'Total Confirmed', x = "")
```

```{r}
#covid_total$total_confirmed - lag(covid_total$total_confirmed)

covid_total <- 
  covid_total %>%
  mutate(new_cases = total_confirmed - lag(total_confirmed))

#head(covid_total)

covid_total %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_point() +
  labs(y = "New Cases", x = "") +
  geom_smooth()
```


```{r, eval = F, echo =F}

covid_total %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_point() +
  geom_smooth(formula = y ~ x + I(x^2), method = lm)

```



# Time Series Analysis


```{r}
covid_ts <- ts(covid_total$total_confirmed)
# plot(covid_ts)
```

## Exponential Forecast

```{r}
library(forecast)

fit_covid_exp <- ets(covid_ts)
fit_covid_arima <- auto.arima(covid_ts)




covid_exp_forecast <- 
  as.data.frame(forecast(fit_covid_exp, 5))

covid_exp_forecast$date <- max(covid_tidy$date) + 1:5

covid_exp_tidy <- 
  covid_exp_forecast %>%
  bind_rows(covid_total) %>%
  arrange(date)
  

covid_exp_tidy %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = total_confirmed)) +
  geom_line(aes(y = `Point Forecast`), colour = "red", linetype = 2) +
  geom_line(aes(y = `Lo 95`), colour = "red", linetype = 3) +
  geom_line(aes(y = `Hi 95`), colour = "red", linetype = 3) +
  labs(y = "Total Confirmed", x = "")
```


## Arima Forecast

```{r}
covid_arima_forecast <- 
  as.data.frame(forecast(fit_covid_arima, 5))

covid_arima_forecast$date <- max(covid_tidy$date) + 1:5

covid_arima_tidy <- 
  covid_arima_forecast %>%
  bind_rows(covid_total) %>%
  arrange(date)
  

covid_arima_tidy %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = total_confirmed)) +
  geom_line(aes(y = `Point Forecast`), colour = "red", linetype = 2) +
  geom_line(aes(y = `Lo 95`), colour = "red", linetype = 3) +
  geom_line(aes(y = `Hi 95`), colour = "red", linetype = 3) +
  labs(y = "Total Confirmed", x = "")
```

# New Cases Forecasts

## Exponential Smoothing

```{r}
library(knitr)
library(kableExtra)

covid_exp_new_cases <- 
  covid_exp_forecast %>%
  mutate(total_confirmed = `Point Forecast`) %>%
  bind_rows(covid_total) %>%
  arrange(date) %>%
  mutate(new_cases = total_confirmed - lag(total_confirmed))
  
covid_exp_new_cases %>%
  filter(date > max(covid_total$date)) %>%
  select(Date = date, `Predicted New Cases` = new_cases) %>%
  kable(caption = "Forcasts Using Exponential Smoothing") %>%
  kable_styling(full_width = F)
```

## Arima

```{r}
covid_arima_new_cases <- 
  covid_arima_forecast %>%
  mutate(total_confirmed = `Point Forecast`) %>%
  bind_rows(covid_total) %>%
  arrange(date) %>%
  mutate(new_cases = total_confirmed - lag(total_confirmed))
  
covid_arima_new_cases %>%
  filter(date > max(covid_total$date)) %>%
  select(Date = date, `Predicted New Cases` = new_cases) %>%
  kable(caption = "Forcasts Using ARIMA Model") %>%
  kable_styling(full_width = F)
```
