---
title: "Untitled"
author: "Aidan Boland"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

energy_types <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/energy_types.csv')
country_totals <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/country_totals.csv')
```

## R Markdown

## Including Plots


```{r}
library(tidyverse)
library(ggplot2)
library(scales)

# Read in data
energy_types <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-04/energy_types.csv')


renewable_percentages <- 
  energy_types %>%
  # First tidy up country names and add a new variable to determine renewable
  mutate(
    country_name = case_when(
      is.na(country_name) == TRUE ~ "United Kingdom",
      TRUE ~ country_name
    ),
    renewable = case_when(
      type == "Conventional thermal" ~ "non_renewable",
      type == "Nuclear" ~ "non_renewable",
      T ~ "renewable")) %>%
  # Group by country and energy type, then calculate totals
  group_by(country_name, renewable) %>%
  summarise(`2016` = sum(`2016`), `2017` = sum(`2017`), `2018` = sum(`2018`)) %>%
  # Transform the data so that totals are in a single column
  pivot_longer(cols = c(`2016`, `2017`, `2018`),
               names_to = "year",
               values_to = "totals") %>%
  # Transform data so that renewable and non renewable totals are in separate cols
  pivot_wider(names_from = renewable, values_from = totals) %>%
  # Calculate percentage using cols from above
  mutate(green_percentage = renewable/(renewable + non_renewable))


renewable_percentages %>%
  filter(country_name %in% c("Ireland", "United Kingdom", "France", "Spain", "Portugal", "Germany", "Denmark", "Netherlands")) %>%
  ggplot(aes(x = reorder(country_name, green_percentage), y = green_percentage, fill = year)) +
  geom_bar(stat = "identity", position='dodge') +
  labs(x = "Country", y = "Percentage Green Engery Produced") + 
  scale_y_continuous(label = percent_format(accuracy = 1)) +
  coord_flip()

renewable_percentages %>%
  filter(year == 2018) %>%
  ggplot(aes(x = reorder(country_name, green_percentage), y = green_percentage)) +
  geom_bar(stat = "identity", position='dodge', fill = "cornflowerblue") +
  labs(x = "Country", y = "Percentage Green Engery Produced", 
       title = "Percentage of green energy in 2018") + 
  scale_y_continuous(label = percent_format(accuracy = 1)) +
  coord_flip()
```




```{r}
library(maps)

world_map <- map_data("world")

renewable_percentages %>%
  filter(year == 2018) %>%
  left_join(world_map, by = c("country_name" = "region")) %>%
  ggplot() + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = green_percentage)) +
  scale_fill_distiller(palette = "Spectral", label = percent_format()) +
  labs(fill = "Percentage Green Enregy Produced") +
  coord_fixed(1.3) +
  theme_void()
```
